services:
  nginx:
    image: nginx:alpine
    ports:  
      - "8080:80"
      - "8443:443"
      - "8000:8000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:  
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build: 
      context: ./sql-challenge-backend
      dockerfile: Dockerfile
    expose: 
      - "8000"
    env_file:
      - ./sql-challenge-backend/.env
    environment:
      - PORT=8000
      - FRONTEND_URL=frontend
      - FRONTEND_PORT=3000
    restart: unless-stopped
    networks:
      - app-network

  frontend:  
    build:  
      context: ./sql-challenge-frontend
      dockerfile: Dockerfile
    expose:  
      - "3000"
    env_file:
      - ./sql-challenge-frontend/.env
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_BASE_URL=https://sql-challenger.ddns.net
      - NEXT_PUBLIC_API_PORT=8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:  
    driver: bridge